name: lombard
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+12

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animations: ^2.0.11
  audio_session: ^0.1.23
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.4.0
  chat_bubbles: ^1.6.0
  clock: ^1.1.1
  collection: ^1.18.0
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  webview_flutter: ^4.4.4
  percent_indicator: ^4.2.5
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  # firebase_core: ^3.9.0
  # firebase_messaging: ^15.1.6
  geolocator: ^11.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0-beta.2
  permission_handler: ^12.0.0+1

  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.8
  freezed_annotation:
  gap: ^3.0.1
  google_fonts: ^6.2.1
  grouped_list: ^5.1.2
  html: ^0.15.4
  http: ^1.2.2
  image_picker: ^1.1.2
  intercepted_client: ^0.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  loader_overlay: ^4.0.2+1
  lottie: ^3.1.2
  local_auth: ^2.3.0
  mask_text_input_formatter: ^2.9.0
  meta: ^1.15.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  pinput: ^5.0.1
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  pure: ^0.3.0
  rxdart: ^0.28.0
  sentry_flutter: ^8.9.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  google_maps_flutter: ^2.12.2
  stack_trace: ^1.11.1
  stream_bloc: ^0.5.3
  talker: ^4.4.1
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_logger: ^4.4.1
  timeago: ^3.7.0
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.20.1
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  lint: ^2.3.0
  ws: ^1.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app.png"
  adaptive_icon_foreground: "assets/images/app.png"
  adaptive_icon_background: "#FF393D"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Inter/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 120
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
